# Site
repository: weprikjm/weprikjm.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ruben Idigora
title: Web/Game Developer
email: ruben.idigora@gmail.com
website: weprikjm.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  weprikjm
linkedin_username: ruben.idigora
youtube_username: globalmtb

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be

# About Section
# about_title: About Me
about_profile_image: images/photo.jpg
about_content: | # this will include new lines to allow paragraphs
  Soy un desarrollador web y de videojuegos con experiencia en el desarrollo de aplicaciones web y en la administración de sistemas informáticos. Me gusta mucho la programación y la tecnología en general.
  Intento comprender lo que necesitan mis clientes y mis compañeros para poder ofrecerles la mejor solución posible. Me gusta trabajar en equipo y aprender cosas nuevas.

content:
  - title: Proyectos # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: ImmoSummer
        link: github.com/weprikjm/ImmoPHPSummer
        # link_text: Project Website
        additional_links:
          - title:  weprikjm/ImmoPHPSummer
            icon: fab fa-github
            url: github.com/weprikjm/ImmoPHPSumme
        quote: >
          Aplicación estilo idealista realizada en el bootcamp de PHP y Laravel de la camara de comercio en Girona.
        description: | # this will include new lines to allow paragraphs
          Proyecto final del bootcamp de PHP y Laravel de la camara de comercio en Girona. Se trata de una aplicación estilo idealista realizada en Laravel con PHP. La aplicación permite a los usuarios registrarse y publicar anuncios de inmuebles. Los usuarios pueden buscar inmuebles por diferentes criterios y contactar con los propietarios de los inmuebles. Los usuarios pueden valorar los inmuebles y los propietarios pueden gestionar sus inmuebles y sus anuncios.
      
      - layout: top-middle
        title: Starcraft Last Hope
        link: http://crandino.github.io/StarCraft/
        # link_text: Project Website
        additional_links:
          - title:  crandino.github.io/StarCraft/
            icon: fab fa-github
            url: http://crandino.github.io/StarCraft/
        quote: >
          Proyecto final de segundo curso del grado de diseño y desarrollo de videojuegos en la UPC.
        description: | # this will include new lines to allow paragraphs
          El proyecto fue realizado dentro de un motor que creamos previamente en C/C++. El motor permitía cargar mapas y sprites y gestionar la lógica del juego. El juego es un RTS en el que el jugador debe gestionar sus recursos y construir unidades para resistir oleadas de ataques enemigos, para encontrar la forma de vencer.

  - title: Experiencia # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: top-middle
        title: Frescmarket
        link: frescmarket.com
        # link_text: boringcompany.com
        sub_title: Director de Informática
        caption: Agosto 2023 - Actualmente
        quote: >
          Producto ecologico y fresco de proximidad a domicilio.
        description: | # this will include new lines to allow paragraphs
          Digitalización de procesos, administración de ecommerce, gestión de servidores y sistemas informáticos, desarrollo de herramientas de gestión interna y de business intelligence. Desarrollo de aplicaciones dockerizadas hechas en Angular, vue y Django.


      - layout: top-middle
        title: Galeo Tech
        link: galeotech.com
        # link_text: boringcompany.com
        sub_title: Programador Web Full Stack
        caption: Octubre 2022 - Febrero 2023
        quote: >
          La importáncia del dato en la toma de decisiones.
        description: | # this will include new lines to allow paragraphs
          Desarrollo de catalogos de datos y otras herramientas de business intelligence para empresas de diferentes sectores del ibex 35. Aplicaciones dockerizadas hechas en Angular, vue y Django.

      - layout: top-middle
        title: Bianna Business
        link: https://bianna.com/en/
        # link_text: boringcompany.com
        sub_title: Programador Web Full Stack Jr
        caption: Enero 2022 - Octubre 2022
        quote: >
          Reciclaje de residuos máquinaria e ingenieria.
        description: | # this will include new lines to allow paragraphs
          Desarrollo de la intranet de la empresa y herramientas de inteligencia artificial. Aplicación dockerizada con Vue y Django. Automatizaciones de procesos usando apis de google como document ai o google drive (gestor documental).

      - layout: top-middle
        title: SkyDive Empuriabrava
        link: https://www.skydiveempuriabrava.com/
        # link_text: boringcompany.com
        sub_title: Administrador de Sistemas y Programador Web
        caption: Setiembre 2019 - Setiembre 2021
        quote: >
          The land of the Sky.
        description: | # this will include new lines to allow paragraphs
          Administrar los sistemas informáticos y servidores de la empresa y desarrollar herramientas para su gestión. Administración del portal web y su mantenimiento. Edición de video de producción.
          Microsoft SQL Server, Windows Server, PHP, Java, Wordpress, Linux, Active Directory, Office 365

      - layout: top-middle
        title: Seur DPD - Girona
        link: https://www.seur.es/
        # link_text: boringcompany.com
        sub_title: Administrador de Sistemas
        caption: Octubre 2017 - Setiembre 2019
        quote: >
          Logística
        description: | # this will include new lines to allow paragraphs
          Administrar los sistemas informáticos y servidores de la empresa, helpdesk y soporte a flota, desarrollar herramientas para integrar clientes a medida (Python), campañas masivas. Instalación de software para la integración B2B de clientes.

  - title: Educación # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: UOC
        caption: 2022 - Actualidad
        sub_title: Grado Multimedia
        quote: >
          Grado en Multimedia
        description: | # this will include new lines to allow paragraphs
          Diseño de contenido multimedia, diseño gráfico, diseño web, diseño 3D, diseño de aplicaciones, diseño de interacción, diseño de interfaces, diseño centrado en el usuario

      - layout: top-middle
        title: CITM UPC
        caption: 2014 - 2017
        sub_title: Diseño y Desarrollo de Videojuegos
        quote: >
          Grado en Diseño y Desarrollo de Videojuegos
        description: | # this will include new lines to allow paragraphs
          Durante mis estudios en la UPC aprendí a desarrollar videojuegos con diferentes motores como Unity, Unreal y Game Maker. También aprendí a programar en diferentes lenguajes como C/C++, C#, Javascript, Python y Lua. Durante mis estudios aprendí a trabajar en equipo y a gestionar proyectos de forma eficiente.

          Destiné gran parte del tiempo libre a participar en game jams y a desarrollar proyectos propios. También destinaba tiempo a estudiar música y la técnica del canto.

      - layout: top-middle
        title: Bootcamp Fundació Esplai PHP y Laravel
        caption: Verano 2019
        sub_title: Programación Web
        quote: >
          Bootcamp desarrollo web
        description: | # this will include new lines to allow paragraphs
          Intensivo de programación web maquetación (HTML, CSS) y javascript, con backend en PHP y Laravel.

  - title: Un poco más sobre mi # Title for the section
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alrededor de la afición a la programación de sistemas y videojuegos, también me gusta la música, el canto, la psicología, la cocina y la naturaleza. También me gusta mucho la tecnología y la informática en general. Me gusta mucho aprender cosas nuevas y me gusta mucho la ciencia ficción:
      - Meditación
      - Diseño de videojuegos
      - Escultura
      - Musica
      - Cocina

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
