# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ruben Idigora
title: Web/Game Developer
email: ruben.idigora@gmail.com
website: weprikjm.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  weprikjm
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: ruben.idigora
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Versátil profesional IT con dedicación al trabajo en equipo y a la satisfacción de los clientes alineado con los objetivos de la empresa.

content:
  - title: Proyectos # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: ImmoSummer
        link: github.com/weprikjm/ImmoPHPSummer
        # link_text: Project Website
        additional_links:
          - title:  weprikjm/ImmoPHPSummer
            icon: fab fa-github
            url: github.com/weprikjm/ImmoPHPSumme
        quote: >
          Aplicación estilo idealista realizada en el bootcamp de PHP y Laravel de la camara de comercio en Girona.
        description: | # this will include new lines to allow paragraphs
          Proyecto final del bootcamp de PHP y Laravel de la camara de comercio en Girona. Se trata de una aplicación estilo idealista realizada en Laravel con PHP. La aplicación permite a los usuarios registrarse y publicar anuncios de inmuebles. Los usuarios pueden buscar inmuebles por diferentes criterios y contactar con los propietarios de los inmuebles. Los usuarios pueden valorar los inmuebles y los propietarios pueden gestionar sus inmuebles y sus anuncios.

  - title: Experiencia # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Galeo Tech
        link: galeotech.com
        # link_text: boringcompany.com
        sub_title: Programador Web Full Stack
        caption: Octubre 2022 - Febrer 2023
        quote: >
          La importáncia del dato en la toma de decisiones.
        description: | # this will include new lines to allow paragraphs
          Desarrollo de catalogos de datos y otras herramientas de business intelligence para empresas de diferentes sectores.

  - title: Educación # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CITM UPC
        caption: 2014 - 2017
        sub_title: Disseny i Desenvolupament de Videojocs
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Durant els meus estudis a la UPC vaig aprendre a desenvolupar videojocs amb diferents motors com Unity, Unreal i Game Maker. També vaig aprendre a programar en diferents llenguatges com C/C++, C#, Javascript, Python i Lua. Durant els meus estudis vaig aprendre a treballar en equip i a gestionar projectes de forma eficient.

          Vaig destinar gran part del temps lliure a participar en game jams i a desenvolupar projectes propis. També destinava temps a estudiar música i la tècnica del cant.

  - title: Una mica més sobre mi
    layout: text
    content: | # this will include new lines to allow paragraphs
      Al voltant de l'afició a la programació de sistemes i videojocs, també m'agrada la música, el cant, la psicologia, la cuina i la natura. M'agrada molt la muntanya i la bicicleta de muntanya. També m'agrada molt la tecnologia i la informàtica en general. M'agrada molt aprendre coses noves i m'agrada molt la ciència ficció:
      - Meditació
      - Música
      - Cant
      - Cuina

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
