# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ruben Idigora
title: Web/Game Developer
email: ruben.idigora@gmail.com
website: weprikjm.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  weprikjm
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: ruben.idigora
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/ruben.jpg
about_content: | # this will include new lines to allow paragraphs
  Versátil profesional IT con dedicación al trabajo en equipo y a la satisfacción de los clientes alineado con los objetivos de la empresa.

content:
  - title: Proyectos # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: ImmoSummer
        link: github.com/weprikjm/ImmoPHPSummer
        # link_text: Project Website
        additional_links:
          - title:  weprikjm/ImmoPHPSummer
            icon: fab fa-github
            url: github.com/weprikjm/ImmoPHPSumme
        quote: >
          Aplicación estilo idealista realizada en el bootcamp de PHP y Laravel de la camara de comercio en Girona.
        description: | # this will include new lines to allow paragraphs
          Proyecto final del bootcamp de PHP y Laravel de la camara de comercio en Girona. Se trata de una aplicación estilo idealista realizada en Laravel con PHP. La aplicación permite a los usuarios registrarse y publicar anuncios de inmuebles. Los usuarios pueden buscar inmuebles por diferentes criterios y contactar con los propietarios de los inmuebles. Los usuarios pueden valorar los inmuebles y los propietarios pueden gestionar sus inmuebles y sus anuncios.
  
  - title: Starcraft Last Hope
    link: http://crandino.github.io/StarCraft/
    # link_text: Project Website
    additional_links:
      - title:  crandino.github.io/StarCraft/
        icon: fab fa-github
        url: http://crandino.github.io/StarCraft/
    quote: >
      Proyecto final de segundo curso del grado de diseño y desarrollo de videojuegos en la UPC.
    description: | # this will include new lines to allow paragraphs
      El proyecto fue realizado dentro de un motor que creamos previamente en C/C++. El motor permitía cargar mapas y sprites y gestionar la lógica del juego. El juego es un RTS en el que el jugador debe gestionar sus recursos y construir unidades para resistir oleadas de ataques enemigos, para encontrar la forma de vencer.

  - title: Experiencia # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Galeo Tech
        link: galeotech.com
        # link_text: boringcompany.com
        sub_title: Programador Web Full Stack
        caption: Octubre 2022 - Febrer 2023
        quote: >
          La importáncia del dato en la toma de decisiones.
        description: | # this will include new lines to allow paragraphs
          Desarrollo de catalogos de datos y otras herramientas de business intelligence para empresas de diferentes sectores.

  - title: Educación # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CITM UPC
        caption: 2014 - 2017
        sub_title: Disseny i Desenvolupament de Videojocs
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Durante mis estudios en la UPC aprendí a desarrollar videojuegos con diferentes motores como Unity, Unreal y Game Maker. También aprendí a programar en diferentes lenguajes como C/C++, C#, Javascript, Python y Lua. Durante mis estudios aprendí a trabajar en equipo y a gestionar proyectos de forma eficiente.

          Destiné gran parte del tiempo libre a participar en game jams y a desarrollar proyectos propios. También destinaba tiempo a estudiar música y la técnica del canto.

  - title: Una mica més sobre mi
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alrededor de la afición a la programación de sistemas y videojuegos, también me gusta la música, el canto, la psicología, la cocina y la naturaleza. Me gusta mucho la montaña y la bicicleta de montaña. También me gusta mucho la tecnología y la informática en general. Me gusta mucho aprender cosas nuevas y me gusta mucho la ciencia ficción:
      - Meditación
      - Música
      - Cocina

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
